logging:
  level:
    root: INFO
    attachment.service.attachmentservice: DEBUG

  file:
    name: logs/attachmentservice.log
    max-size: 10MB
    max-history: 30

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

loggers:
  error:
    file:
      name: logs/error-attachmentservice.log
      max-size: 10MB
      max-history: 30
      pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
